# Use this file to select and deselect buildings to be imported
# TODO: Eventually make this nicer to use (maybe ask users for a mask?)
paths = [
    "allensville",
    "beechwood",
    "benevolence",
    "coffeen",
    "collierville",
    "corozal",
    "cosmos",
    "darden",
    "forkland",
    "hanson",
    "hiteman",
    "ihlen",
    "klickitat",
    "lakeville",
    "leonardo",
    "lindenwood",
    "markleeville",
    "marstons",
    "mcdade",
    "merom",
    "mifflinburg",
    "muleshoe",
    "newfields",
    "noxapater",
    "onaga",
    "pinesdale",
    "pomaria",
    "ranchester",
    "shelbyville",
    "stockman",
    "tolstoy",
    "uvalda",
    "wainscott",
    "wiconisco",
]
